apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.configmapName" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
{{- if .Values.env }}
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
  {}
{{- end }}
